services:
  backend:
    container_name: sentinellog_intake
    build: .
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend-intake:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS_INTERNAL=${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}
    networks:
      - sentinel-net
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
  worker:
    container_name: sentinellog_worker
    build: .
    restart: always
    command: python app/workers/worker.py
    volumes:
      - ./backend-intake:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS_INTERNAL=${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}
      - KAFKA_BOOTSTRAP_SERVERS_EXTERNAL=${KAFKA_BOOTSTRAP_SERVERS_EXTERNAL}
      - POSTGRES_DSN=${POSTGRES_DSN}
    networks:
      - sentinel-net
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: sentinel-broker-redpanda
    hostname: redpanda
    command:
      - redpanda
      - start
      - --mode=dev-container
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://127.0.0.1:19092
    ports:
      - "19092:19092" #just for debugging
    networks:
      - sentinel-net

  postgres:
    image: postgres:16-alpine
    container_name: sentinel-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - sentinel-net

networks:
  sentinel-net:
    driver: bridge

volumes:
  postgres_data:
